package com.minisal.timeline;
import org.apache.xerces.xs.datatypes.ObjectList;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.sql.Array;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;


@Controller  // This means that this class is a Controller
@RequestMapping(path="/message") // This means URL's start with /timeline (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MessageRepository messageRepository;



    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewMessage (
              @RequestParam String user,
              @RequestParam String content) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Date addDate = new Date( );
        SimpleDateFormat dateFormat = new SimpleDateFormat ("yyyy-MM-dd HH:mm:ss");

        Message m = new Message();
        m.setUser(user);
        m.setContent(content);
        m.setAddTime(dateFormat.format(addDate));
        messageRepository.save(m);
        return "Saved";
    }

    @GetMapping(path="/getNow")
    public @ResponseBody Iterable<Message> getNowMessage() {
        // This returns a JSON or XML with the message
        String today = "2019-10-24 13:00:00";
        String oneDayBefore = "2019-10-23 13:00:00";
        return messageRepository.findByIdGreaterThanAndIdLessThan(15,20);
    }


    @GetMapping(path="/getNew")
    // nowTime = "2019-10-25 13:00:00"
    public @ResponseBody Object getNewMessage(@RequestParam Integer messageId) {
        // This returns a JSON or XML with the message
        return messageRepository.findByIdGreaterThanAndIdLessThan(messageId,messageId+5);
    }

    @GetMapping(path="/getOld")
    public @ResponseBody Iterable<Message> getOldMessage(@RequestParam Integer messageId) {
        // This returns a JSON or XML with the message
        return messageRepository.findByIdGreaterThanAndIdLessThan(messageId-5,messageId);
    }


}



